version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # this creates an anonymous mount to platform dependent node_modules, ignoring the local folder
    environment:
      - APP_ENV=local
    command: yarn run start:docker-compose
    ports:
      - 3000:3000
    depends_on:
      # - postgres
      postgres:
        condition: service_healthy
  postgres:
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_PASSWORD: pokemon_password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      retries: 15
      start_period: 15s
      timeout: 10s
    